import { promises as fs } from "node:fs"
import path from "node:path"

import { rimraf } from "rimraf"
import { type Registry, registrySchema } from "shadcn/schema"

import { getAllBlocks } from "@/lib/blocks"

const REGISTRY_PATH = path.join(process.cwd(), "src/__registry__")
const PUBLIC_REGISTRY_PATH = path.join(process.cwd(), "public/r")

/**
 * Build src/__registry__/registry.autogenerated.json, src/__registry__/index.tsx
 * Thanks @shadcn/ui
 */
export async function buildRegistry(registry: Registry) {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {`
  for (const item of registry.items) {
    if (!Array.isArray(item.files) || !item.files?.length) {
      continue
    }

    const componentFilePath = item.files[0].path
    const componentPath = componentFilePath.startsWith("src/")
      ? componentFilePath.replace("src/", "@/")
      : `@/registry/${componentFilePath}`

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    files: [${item.files.map((file) => {
      const filePath = file.path.startsWith("src/")
        ? file.path
        : `src/registry/${file.path}`
      return `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}",
    }`
    })}],
    component: React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`
  }

  index += `
}`

  // Build /src/__registry__/registry.autogenerated.json
  const registryJSON = JSON.stringify(
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: "ncdai",
      homepage: "https://chanhdai.com/components",
      items: registry.items
        .filter((item) => item.type !== "registry:example")
        .map((item) => {
          return {
            ...item,
            author: item.author ?? "ncdai <dai@chanhdai.com>",
            files:
              item.files?.map((file) => {
                if (file.path.startsWith("src/")) {
                  return file
                }

                return {
                  ...file,
                  path: `src/registry/${file.path}`,
                }
              }) ?? [],
          }
        }),
    },
    null,
    2
  )

  await rimraf(path.join(REGISTRY_PATH, "registry.autogenerated.json"))
  await fs.writeFile(
    path.join(REGISTRY_PATH, "registry.autogenerated.json"),
    registryJSON,
    "utf8"
  )

  // Build public registry
  await rimraf(path.join(PUBLIC_REGISTRY_PATH, "registry.json"))
  await fs.writeFile(
    path.join(PUBLIC_REGISTRY_PATH, "registry.json"),
    registryJSON,
    "utf8"
  )

  // Build /src/__registry__/index.tsx
  await rimraf(path.join(REGISTRY_PATH, "index.tsx"))
  await fs.writeFile(path.join(REGISTRY_PATH, "index.tsx"), index, "utf8")
}

async function buildBlocksIndex() {
  const blocks = await getAllBlocks(["registry:block"])

  const payload = blocks.map((block) => ({
    name: block.name,
    description: block.description,
    categories: block.categories,
  }))

  // Build /src/__registry__/__blocks__.json
  await rimraf(path.join(REGISTRY_PATH, "__blocks__.json"))
  const blocksJsonPath = path.join(REGISTRY_PATH, "__blocks__.json")
  await fs.writeFile(blocksJsonPath, JSON.stringify(payload, null, 2))
}

try {
  console.log("💽 Building registry...")

  const { registry } = await import("@/registry/index")

  const result = registrySchema.safeParse(registry)

  if (!result.success) {
    console.error(result.error)
    process.exit(1)
  }

  await buildRegistry(result.data)

  await buildBlocksIndex()

  console.log("✅ Done!")
} catch (error) {
  console.error(error)
  process.exit(1)
}
